[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_FORCE_NETLIFY = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_FORCE_NETLIFY = "1"
